class Pichu
    def self.frame_one
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkxl;,;kWMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl,.     .xWMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.         lNMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMWKkKWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKWMMWx.          .xWMMMMMMMMMMMMMMMMMMMMM
        MMMMMWKl,. .,;lkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl,..;x0l.           lNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMWl         .,l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl.      .,,.           lWMMMMMMMMMMMMMMMMMMMMMM
        MMMMMWl            .,lKWMMMMMMMMMMMMMMMMMMMMMMMWKxd;          .dc           lWMMMMMMMMMMMMMMMMMMMMMM
        MMMMMWl               .lKWMMMMMMMMMMMMMMMMMMWKl,.              cc           lWMMMMMMMMMMMMMMMMMMMMMM
        MMMMM0;         'ooo:'. .lKWMMMMMMMMMMMMMMMWx.     ..          cd.          lWMMMMMMMMMMMMMMMMMMMMMM
        MMMMWl          :0KKK0ko:,;oKMMMMMMMMMMMWKkl. .':odx:          .dc        .;kWMMMMMMMMMMMMMMMMMMMMMM
        MMMMWl    ,ooo:.,kKKKKKKK0kcoKWMMMMMMMMWx. .:ok0KKKKo.  .':;.   cc  .,lxkkKWMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMWl   ,kKKK0kk0KKKKKKKKK0klkWMMMMMMKl..:k0KKKKKKK0c.:k0K0o.  ,llkKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMWl   c0KKKKKKKKKKKKKKKKK0o;kWMMMMK:.:k0KKKKKKKKKKOk0KKKK0o. ;KWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMWK; ,kKKKKKKKKKKKKKKKKKKK0coWMMW0:;x0KKKKKKKKKKKKKKKKKKKK0: ;xl;;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMWl.:0KKKKKKKKKKKKKKKKKKK0doKMMWo;xKKKKKKKKKKKKKKKKKKKKKK0c ..   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMW0;.o0KKKKKKKKKKKKKKKKKKK0c:xkx;.o0KKKKKKKKKKKKKKKKKKKKKKk;cc   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMWl.:0KKKKKKKKKKKKKKKKKKK0c      ,kKKKKKKKKKKKKKKKKKKKKKKx;lc  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMWK:;xKKKKKKKKKKKKKKKKKKK0c,:,::'.;kKKKKKKKKKKKKKKKKKKKKk;',. .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMKo;o0KKKKKKKKKKKKKKKKK0dd0KKK0kld0KKKKKKKKKKKKKKKK0kccdd:. lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMWKxddk00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000ko:..ck00o.;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMWWKkxddddOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0dloo,     .o00kc;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWWNk:ckKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOk00x:.   .o0KK0c:xKWWMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMKod0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0:   :0KKKKk,.,coKWMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNol0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o.  :0KKKKKk;cxc;oKWMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWklkKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0:  c0KKKKK0dlk0kddkKWMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWoc0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o. ,xKKKKKKK0cl0KK0klkWMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWoc0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o. :0KKKKKKK0cc0KKKKkloKWMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWoc0KKKKKKK0KKKKKKKKKKKKKKKKKKKK000KKKKKKKKx,  :0KKKKKK0o.c0KKKKKx;oNMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWklkKKKkoc,,ckKKKKKKKKKKKKKKKKkc,,,coxkxxd:.   :0KKKKKK0: :0KKKKK0c'xWMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMWklk0Oc:d,  c0KKKKKKKKKKKKKK0c:d,  .';,,.    .o0KKKKKKx,.o0KKKOdx:'xWMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMWk:cc,',. .oKKKKKKKKKKKKKKK0o;;..........':ok0KKKKK0o..l0Kkk0kl:,oWMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMWKdc;..;ok0KKKKKKKKKKKKKKKK0koodc'..,:co0KKKKKKKKkdxxoldo:,cxx:;kWMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMWKdcldk0K0KKKOddkKKKK0000kdccc;cx00ll0KKK0kdddokWMWWKolc;cloKWMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMWWKOxdlcoddl;;lddoccooodddk00KK0o.;oddddlokKWWMMMMMWWWWWWWMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMWW0lcodddddddc;o000KKKKKKKkc;lkkkOKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKod0KKKKKK0cl0KKKKKKKKk;'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxld0KKKK0ocx0KKKKKxo;;ONNNNNNNNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0occoooc::::cdddo:,:dO00000000000KKKKKKXXXNWWMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKko:,:lxOOxooooxOOOOO00OOOOOOOO000000000KKNWMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXXXXXXXXXKKKKKKKKKKKKXXXXXXXXXNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   

    ".colorize(:yellow)
    sleep (0.15)
    system 'clear'
  end

  def self.frame_two
    puts "
   
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkxl;,;kWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl,.     .xWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.         lNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWKkKWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKWMMWx.          .xWMMMMMMMMMMMMM
MMMMMMMMMMMMMWKl,. .,;lkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl,..;x0l.           lNMMMMMMMMMMMMMM
MMMMMMMMMMMMMWl         .,l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKkl.      .,,.           lWMMMMMMMMMMMMMM
MMMMMMMMMMMMMWl            .,lKWMMMMMMMMMMMMMMMMMMMMMMMMWKx;          .dc           lWMMMMMMMMMMMMMM
MMMMMMMMMMMMMWl               .lKWMMMMMMMMMMMMMMMMMMMWKl,.             cc           lWMMMMMMMMMMMMMM
MMMMMMMMMMMMM0;         'loo:'. .lKWMMMMMMMMMMMMMMMMWx.    ..          cd.          lWMMMMMMMMMMMMMM
MMMMMMMMMMMMWl          :0KKK0ko:,;oKWMMMMMMMMMMWKkkl. .':ox:          .dc        .;kWMMMMMMMMMMMMMM
MMMMMMMMMMMMWl    ,ooo:.,xKKKKKKK0kcoKWMMMMMMMMWx.  .:ok0KK0o.  .'::.   cc  .,lxkkKWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWl   ,kKKK0kk0KKKKKKKKKKklkWMMMMMMKl..':x0KKKKKK0c.:k0K0o.  ,lokKWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWl   c0KKKKKKKKKKKKKKKKK0o;kWMMMMK:.:k0KKKKKKKKKKOk0KKKK0o. ;KWWWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWK; ,kKKKKKKKKKKKKKKKKKKK0coWMMW0:;x0KKKKKKKKKKKKKKKKKKKK0: ,xl;;kWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWl.:0KKKKKKKKKKKKKKKKKKK0doKMMWo;xKKKKKKKKKKKKKKKKKKKKKK0c ..   lWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMW0;.o0KKKKKKKKKKKKKKKKKKK0c:xkx;.o0KKKKKKKKKKKKKKKKKKKKKKx;cc   lWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWl.:0KKKKKKKKKKKKKKKKKKK0:      ,kKKKKKKKKKKKKKKKKKKKKKKx;lc  .xWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMK:;xKKKKKKKKKKKKKKKKKKK0c.'''''.;kKKKKKKKKKKKKKKKKKKK0k;',. .xWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMKo:o0KKKKKKKKKKKKKKKKK0dd00000xld0KKKKKKKKKKKKKKKK0klcoo:. lWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWKxddk00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000ko:,,o0K0o.;0WMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWKkdddddOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0dcoo,    c0KK0kc;kWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWWNk:ckKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOk00k:.  :0KKKK0coNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMKod0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0:  :0KKKKKkloKMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNol0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo. :0KKKKKKk;oWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWklkKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0:.c0KKKKKKKdoKWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWoc0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo. ,xKKKKKKK0c:KWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWoc0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o.  .o0KKKKK0:.;KMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWoc0KKKKKK00KKKKKKKKKKKKKKKKKKKKK000KKKKKK0x,  .:kKKKKK0o;:;oNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWklkKKKkoc,,ckKKKKKKKKKKKKKKKKKkddc,cxOxxd:. .:k0KKKKKK0ccOklkWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWklk0Oc:d,  c0KKKKKKKKKKKKKKK0c:d,  ';,,. .:x0KKKKKKKKk:l00c:0WMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWk:cc,',. .o0KKKKKKKKKKKKKKK0o.  .......:kKKKKKKKKK0dldkK0c'xWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWKdc;..;ok0KKKKKKKKKKKKKKKKK0kdodc...:okKKKKKKKK0kddkKKK0c:0MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdcldk000KKKOddOKKKK00000kdlc:cokOll0KKK0kddocd0KKKK0coNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxdlcoddl;;lddoccoooodddk0KK0o.,oodddc.;k0KKKKK0x;oWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKlcodddddddc;oO0K0KKKKKKkc,;:..c0Xd.:kO0Ok00o:oKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoo0KKKKKK0clO0KKKKKKKk;.;l::xO00x,.:xx;,:cdKWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXklco0KKKK0ocok0KKKK0x;,dOOOOOOO0Ox::l:,:lx0XWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0xlccoooc::,::coddo::xO00O000000OOOOOOO00KXWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXOxl:cdk00OxooooxOO0000000000KKKKXXXNNWWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWNNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

    ".colorize(:yellow)
    sleep (0.15)
    system 'clear'
  end


def self.frame_three
    puts "

    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKl;,;lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMWKl,.     ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMWKl.         .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWKl.            lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMWx.   .;'   .'.  .xWMMMMMMMMMMMMMMMWWWWKkkkkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMWKl. .:ok0o..:k0o.  lWMMMMMMMWWWKkkxl;,,,.        .xWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWKo'.'ck0KKK0kk0KK0o. .xWMMMWKkl;;.                  lWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMWx;cok0KKKKKKKKKKKKK0:  lWWKl;.   .''',:oo:.          lWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMKo;o0KKKKKKKKKKKKKKKK0o. l0o;,:ooodk0000KKK0:    ..   ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMWo;xKKKKKKKKKKKKKKKKKKKx' cl;x0KKKKKKKKKKKKK0dcoodx:   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMWoc0KKKKKKKKKKKKKKKKKK0: .dlc0KKKKKKKKKKKKKKKKKKKK0:   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMWoc0KKKKKKKKKKKKKKKKKkc.;00ld0KKKKKKKKKKKKKKKKKKKKo.  ;KWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMWklkKKKKKKKKK00kddddo,.;0Ndl0KKKKKKKKKKKKKKKKKKKK0:  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMNol0KKK0kddlcoddddddoccdx:c0KKKKKKKKKKKKKKKKKKK0o.  lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMWKookddoddddk0KKKKKKKK00kddddkKKKKKKKKKKKKKKKK0o.  ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMNo;clk0KKKKKKKKKKKKKKKKKKKkllk0KKKKKKKKKKK0ko:. .lKWMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMKolodk0KKKKKKKKKKKKKKKKKKKKKK0dcco0KK00kdooc,..,;lKWMMMMMMMKo;;lxkKWMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMWKocx0KKKKKKKKKKKKKKKKKKKKKKKKKKK0o;:lccdl::okkkKWWMMMMMMMMMNl      .lkKWMMMMMMMMMMMMMM
    MMMMMMMMMMMWKolk0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kc,.lXNNNWMMMMMMMMMMMMMMWx.         .l0WMMMMMMMMMMMM
    MMMMMMMMMMWKockKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0Oc.;ldxxkOKWMMMMMMMMMMNl            .,lKWMMMMMMMMM
    MMMMMMMMMWKcc00kdccx0KKKKKKKKKKKKKKKKKKKK0kddk0KKK0k, :00kddlokkkkKWWWMWx.               .lKWMMMMMMM
    MMMMMMMMMWo;x0dlOc .o0KKKK00KKKKKKKKKKKKkdxk;.:kKKK0: ,kKKKKko,   .,,;lc.                  .xWMMMMMM
    MMMMMMMMMWo;dd:',. .o0KKKkddkKKKKKKKKKK0l:xx,  c0KK0:  ,xKKKKKk:.           ..              .xWMMMMM
    MMMMMMMMMWo.,,,...:k0KKkdooooooodkKKKKKKkc.   'lxO00:   .o0KKKK0:         .l00;              .lKMMMM
    MMMMMMMMMWo.',,',o0KKK0:      ...c0KKKKKK0d,.',,,:cl'  .:kKKKKKKko,;c;,. ;0WMWl              .lKMMMM
    MMMMMMMMMWk,'',',o0KKK0:   ...''.c0KKKKKK0o;,,,,'...  'x0KKKKKKKK0loNWWKkKWMMMK;           .lKWMMMMM
    MMMMMMMMMMWo..,:oO0KKK0c  .',,,'.c0KKKKKK0o;,,,,'.    .:kKKKKKKKKKklkWMMMMMMMMWl          .xWMMMMMMM
    MMMMMMMMMMWKl',o0KKKKKKk;..',,'..c0KKKKKK0Oo:,,'.      .o0KKKKKKKKk;oWMMMMMMMMW0;      .lkKWMMMMMMMM
    MMMMMMMMMMMMWKo;cx0KKKKKkc,''..'ckKKKKKKKKK0d'.  .''',ck0KKKKKKKK0c:0WMMMMMMMMMWl   .lkKWMMMMMMMMMMM
    MMMMMMMMMMMMMMWx'.':ok00K0kddddk0KKKKKKK00k:. .:ok0000KKKKKKKKKKKk,'lKWMMMMMMMMWk;;lKWMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMW0:.. .',:ooooodk0kooooo:,'. .:kKKKKKKKKKKKKKKKK0x;;lclKWMMMMMMMMMWWMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMWKl::,'.       .'.        .:kKKKKKKKKKKKKKKKK0kc;ckK0o:xWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMWocO00ko:,'.            .o0KKKKKKKKK0ocx0koc:ccx0KKK0o;kWMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMKodKKKKK00k:.   .':l:,,o0KKKKKKKKKkdlldxxl':OKKKKKKko,oWMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWklkKKKKKK0c;c;;cddd,.c0KKKKKKK00kokNWWWWWKxdk0KKkdo:.lWMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMWk:o0KKKK0loNWWWWWNl;xKKKKK0kdxdkKWMMMMMMMWKkdddc..';kWMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMW0ld0KKK0o;oKWMMMWoc00000kc;kWWWMMMMMMMMMMMMWKOkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMWo;xkdkOc:kXMMMMWklcldlcloKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMWK:.;oxdlkWMMMMMMWKOKNKKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMKkKWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXKKKKK00000000000000000KKKKKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNK000O00O0000000OOOOOOOOOOOOO000O000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKK000000000000OOOOOO00OO0000000KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNXXXXXXKKKKKKXXXXXXXXNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    
    
    ".colorize(:yellow)
    sleep (0.15)
    system 'clear'
  end
  
  def self.frame_four
    puts "
    MMMMMMMMMMMMMMMMMMMMMMMWKkl.   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMWKl.       .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMWKl.           lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMWKl.   ..        ;0MMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMW0;  .'cx:  .::.   lWMMMMMMMMMMWWWNKkkkxl;,,,,,,;lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMWKl. .:x0KKkccx00x,  ;KMMMMMMWKkl;,,,.              lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMWKo;,:ok0KKKKKKKKKKKk,  lWMWKkl,.      .''.           lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMW0:;x0KKKKKKKKKKKKKKK0c  lNKl'.'',:oooodk00x,         .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMWk;ckKKKKKKKKKKKKKKKKKKx' cx;:ok00KKKKKKKKKK0c.''';'   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMWoc0KKKKKKKKKKKKKKKKKK0o. clc0KKKKKKKKKKKKKKKkk0000:   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMWoc0KKKKKKKKKKKKKKKKK0x,.lOol0KKKKKKKKKKKKKKKKKKKKk,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMWoc0KKKKKKKKKKKK00000o..xNklkKKKKKKKKKKKKKKKKKKKK0c   lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMKld0KKKKK00kdddooooo:.;k0lc0KKKKKKKKKKKKKKKKKKKKk,  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMWklk00kddooccdk000000kdddcck0KKKKKKKKKKKKKKKKKKk,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMWococodk000KKKKKKKKKKKKK0kdld0KKKKKKKKKKKKKK0x,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMWKklcok0KKKKKKKKKKKKKKKKKKKK0klcdOKKKKK0K00koc,. .l0WMMMMMMMMMMMMMMMMMWWKkkkKWWWMMMMMMMMMM
    MMMMMMMMMWk:ck0KKKKKKKKKKKKKKKKKKKKKKKKKko;;xkddc;,,cl;;lxkKWMMMMMMMMMMMMMMMWKkl;,.   .,,;lxkKWMMMMM
    MMMMMMMWKxdk0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKkc,.:kkkkkKWWWWMMMMMMMMMMMMMMMMMWKl.               .;lkKMM
    MMMMMMWk:o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKx,;xkkkOKWWMMMMMMMMMMMMMMMWWKl,.                     lWM
    MMMMMWklkKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o. ,odddddxKWWWWWMMMMMMMKl,.                        lWM
    MMMMWx;oxddlcx0KKKKKKKKKKKKKKK0kOKOk0KKKKKKKK0:.:0KKK00dcc;,;lxkkK0kx;                          ;0WM
    MMMMWo':,,c:,ckKKKOdddOKKKKKKkc;cdc;cxkxxxxO00: .lO0KKKK0o.      ..        .,lxl,.             ;KWMM
    MMMMWl.',,:d00KKK0kdddk0000KKkdk000d;;;,,,,:co,  .':k0KKK0x,            .,oKWMMWWKkl,.         lWMMM
    MMMMWo.',,,:x0KKkc,''''''',o0KKKK0kl,,,,,,,,,'.    .o0KKKK0o,...     .lkKWMMMMMMMMMMWKkl.     ;KMMMM
    MMMMWo.',,,,o0KK0:         :0KKKK0o;,,,,,,,,,.  .:ok0KKKKKKKOcl0kxl;lKWMMMMMMMMMMMMMMMMWKl.  ;KMMMMM
    MMMMWK:.',,:x0KK0c    ....'o0KKKK0o;,,,,,,,,'.  'x00KKKKKKKK0dlkkKWWWMMMMMMMMMMMMMMMMMMMMW0l;kWMMMMM
    MMMMMWk,.':d0KKKKk:....',lk0KKKKK0kl,,,,,,,'.    .;o0KKKKKKKKOc,,'l0WMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMM
    MMMMMMWKo,;x0KKKKKKkddddk0KKKKKKKK0koc;,''..    .:dkKKKKKKKK0o;oxoc;xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMNc .:ok0KKKKKKKKKKKKKKKK00kdooc:;;,',:ookKKKKKKKKKKK0cc0KK0xloKMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMWx...  .,:ook000000KKK0kc,,;o000000000KKKKKKKKKKKKKK0o;o0KKKKx;:KWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMWl .:,,'    .''''',:o:'.,::clxdccd0KKKKKKKkdldKKKKKkc.,x000K0x:.oWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMK:,xkko:,,;'.          :0K0Okkxoldk0KKKKk;.;kK0kdc;lxkkdlcc,,;oKMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMKo;cdkOkk0Ol..cl;,,;,.,x0KKKKK0kc;o0K0x;',cocclokKWMMMWKkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMWKkoldxxxdloKWWWWWWWKo;cdk00K0KOc;oclxkkOkkkKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMWKkkxxdxxxdlokkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWNNXKKKKK00000000000000000KKKKKXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMNK0000OOO00000OOOOOOOOOOOOOOOOOO0000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWXKK000000000000OOOOOOO0000000000KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNXXXXXXKKKKKKKXXXXXXXNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

    ".colorize(:yellow)
    sleep (0.15)
    system 'clear'
  end
  
  def self.frame_five
    puts "
   

    MMMMMMMMMMMMMMMMMMMMMWKxl.   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMW0l.       .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMWKl.           lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMKl.   ..        ;0MMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMW0;  .'cx:  .::.   lWMMMMMMMMMWWWWKkkkkxl;,,,,,,;lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMWKl. .:x0KKkccx00x,  ;0WMMMMMWKkl;,,.               lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMKo;,:ok0KKKKKKKKKKKk,  lWMWKxl;.     .'''.           lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMW0:;x0KKKKKKKKKKKKKKK0c  lNKl'.'',:ooodk000x,         .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWk;ckKKKKKKKKKKKKKKKKKKx, cx;cok000KKKKKKKKK0c.'',;'   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWoc0KKKKKKKKKKKKKKKKKK0o. clc0KKKKKKKKKKKKKKKkk0000:   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWoc0KKKKKKKKKKKKKKKKK0x,.l0ol0KKKKKKKKKKKKKKKKKKKKk,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWol0KKKKKKKKKKKK00000o..xNklkKKKKKKKKKKKKKKKKKKKK0c   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWKod0KKKKK00kdddooooo:.;k0lc0KKKKKKKKKKKKKKKKKKKKk,  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMWklk00kddooccdk000000kdddcck0KKKKKKKKKKKKKKKKKKk,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMNococodk000KKKKKKKKKKKKK0kocd0KKKKKKKKKKKKKK0x,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWKklcok0KKKKKKKKKKKKKKKKKKKKKklcdOKKKKK0000koc,. .lKWMMMMMMMMMMMMMMMMMWWKkkkKWWWMMMMMMMMMMMM
    MMMMMMMWk:ck0KKKKKKKKKKKKKKKKKKKKKKKKKko;;xkddc;,col;;lxkKWMMMMMMMMMMMMMMMWKkl;,.   .,,;lxkKWMMMMMMM
    MMMMMWKxdk0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKkc,.:kkkkKNWWWMMMMMMMMMMMMMMMMMMWKl.               .,lkKMMMM
    MMMMWk:o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKx;;xkkOKWWWWMMMMMMMMMMMMMMMWKl,.                     lWMMM
    MMMWklkKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o. ,odddddxKWWWWWMMMMMMMKl,.                        lWMMM
    MMWk;lxddccx0KKKKKKKKKKKKKKK0kOKOk0KKKKKKKK0: :0KK000olc;,;lxkkKKkx;                          ;KMMMM
    MMWo':,,c:,ckKKKOdddOKKKKKKkc;coc;ckkxxxxO00: .o0KKKKK0o.      ..        .,lxl,.             ;0WMMMM
    MMWo.,,,:d00KKK0kdodk0000KKkdk000d;;;,,,,:cl,  .:k00KKK0x,            .,l0WMMMWKkl,.         lWMMMMM
    MMWo.,,,,:x0KKkc,''''''',o0KKKK0kl,,,,,,,,,'.   .o00KKKK0o,...     .lkKWMMMMMMMMMMWKkl.     ;KMMMMMM
    MMWo.',,,,o0KK0:         :0KKKK0o;,,,,,,,,,.  .:kKKKKKKKKKOcl0kxl;lKWMMMMMMMMMMMMMMMMWKl.  ;KMMMMMMM
    MMWK:.',,:x0KK0c    ....'o0KKKK0o;,,,,,,,''.  'x0KKKKKKKKK0dlkkKWWWMMMMMMMMMMMMMMMMMMMMWKl;kWMMMMMMM
    MMMWx,.,:x0KKKKkc....',lk0KKKKK0kl;,,,,,,'.    .o0KKKKKKKKKOc,,'lKWMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMM
    MMMMWKo,;x0KKKKKKkddddk0KKKKKKKK0koc;,''..    .:kKKKKKKKKK0o;oxoc:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMNc .:ok0KKKKKKKKKKKKKKKK00kdolc:;;,,,:odkKKKKKKKKKKK0cc0KK0xloKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMWx...  .':ook000000KKK0kc,,;o000000000KKKKKKKKKKKKKK0o;o0KKKKx;:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMWl .:,,'    .''''',:o:'.,::clxdccd0KKKKKKKkld00KKK0kc.,x00KK0x:.oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMWK:,xkko:,,;'.          :0K0Okkxocdk0KKKKk;;x0K0kdc;lxkxdlc:,,;oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMKo;cdkOkk0Ol..cl;,,,,.,xKKKKKK0kc;o0K0x;'coocclokKWMMMWKkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWKkoldxxddloKWMWWWWWKo;cdk0K000Oc;oclxkkkkkkKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMWWWWWWWMMMMMMMMMMWKkkxxxxxddlokkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMWWNNNNXXXXXXKKKKKKKXXXXXXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMWXKK00000000000OO000000000000000KKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMNK00OOOOOOOOO00OOOOOOO00OOOOOOO00000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWNNXKKKKK00000000000000000KKKKXXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    ".colorize(:yellow)
    sleep (0.15)
    system 'clear'
  end
  


  def self.animation
    10.times do
      Pichu.frame_one
      Pichu.frame_two
      Pichu.frame_three
      Pichu.frame_four
      Pichu.frame_five
    #   Pichu.frame_six
    #   Pichu.frame_seven
    #   Pichu.frame_eight
    #   Pichu.frame_nine
    end
  end

  def self.go
    system 'clear'
    puts "\n\n RUN PICHU! RUN!!!  \n\n"
    self.animation
  end

end
